### PR TITLE
C

### PR DESCRIPTION
**Pull request by profumato4**
C

### CODE REVIEW

**Comment by chaudharypraveen98** [comment]
- Closes #13 
- Closes #20 
- Closes #23 
- Closes #26 
- Closes #27 
- Closes #28 
- Closes #29 
- Closes #30 
- Closes #221

**Comment by chaudharypraveen98** [comment]
@profumato4 If you have time just mention the issues like I have mentioned in your comment. By this once I merge it, All linked issues will be closed automatically

**Comment by chaudharypraveen98** [comment]
And really thanks for your conribution, Hope i will make a repo that will surely help others in future.

**Comment by profumato4** [comment]
i dont know how to mention

**Comment by chaudharypraveen98** [comment]
Okay no issues.

**Pull request merged**
