### PR TITLE
Profumato4

### PR DESCRIPTION
**Pull request by profumato4**
I created the sql/hackerrank folder with all the sql questions present on hackerrank, if you want, create the excel file and add it to the readme (obviously I created all the various readmes for the questions)

### CODE REVIEW

**Comment by chaudharypraveen98** [comment]
@profumato4 Hey Lenny, I think we should not mix competitive programming with sql questions. It will be more sort of confusing. I propose that we should create a new repo called "Databases Interview Challenges". What do you think?

**Comment by profumato4** [comment]
For me is fine tell me what you prefer to do, the repository is yours

**Comment by chaudharypraveen98** [comment]
I prefer, creating the new one.

https://github.com/chaudharypraveen98/Databases-Interview-Challenges

You can add all the sql question there. I will setup the plan in some time. I have invited you as a collaborator. 

You can modify the this pr or want me to close this, so that you can open new one. Do let me know.

**Comment by profumato4** [comment]
I close the pr here and open it on the new repository

**Pull request closed without merging**
