### PR TITLE
Profumato4

### PR DESCRIPTION
**Pull request by profumato4**
java

### CODE REVIEW

**Comment by chaudharypraveen98** [comment]
Great Man

**Comment by profumato4** [comment]
fill the status in the excell file

**Comment by chaudharypraveen98** [comment]
I think, I had already provided access. Please check and do let me know

**Comment by profumato4** [comment]
i mean you have to fill the cell : "Status (To be filled by repo owner)" I alredy filled my thing

**Comment by chaudharypraveen98** [comment]
Oh, I have gone through some of your submission, you have added comments and tried on hackerrank and they passes the test cases so changed the status to done.

**Comment by chaudharypraveen98** [comment]
- Closes #199

**Comment by chaudharypraveen98** [comment]
@profumato4 

You can closes issues like this

```
This PR addresses several issues:

- Closes #101
- Closes #202
- Closes #303
```

**Comment by chaudharypraveen98** [comment]
- Closes #153 
- Closes #206

**Pull request merged**
